// SPDX-FileCopyrightText: 2022 Alex Evgrashin <aevgrashin@yandex.ru>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 no <165581243+pissdemon@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client._Mini.GhostRolePurchase;
using Content.Shared._Mini.GhostRolePurchase;
using Content.Shared.Ghost.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles;

[GenerateTypedNameReferences]
public sealed partial class GhostRoleEntryButtons : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    private readonly GhostRoleKind _ghostRoleKind;
    private readonly uint _playerCount;
    private readonly TimeSpan _raffleEndTime = TimeSpan.MinValue;
    private readonly bool _isPurchasableRole;
    private readonly int _rolePrice;
    private readonly GhostRoleInfo _ghostRoleInfo;

    public GhostRoleEntryButtons(GhostRoleInfo ghostRoleInfo)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _ghostRoleInfo = ghostRoleInfo;
        _ghostRoleKind = ghostRoleInfo.Kind;
        if (IsActiveRaffle(_ghostRoleKind))
        {
            _playerCount = ghostRoleInfo.RafflePlayerCount;
            _raffleEndTime = ghostRoleInfo.RaffleEndTime;
        }

        _isPurchasableRole = IsPurchasableRole(ghostRoleInfo);
        _rolePrice = GetRolePrice(ghostRoleInfo);

        UpdateRequestButton();
    }

    private void UpdateRequestButton()
    {
        var messageId = _ghostRoleKind switch
        {
            GhostRoleKind.FirstComeFirstServe => "ghost-roles-window-request-role-button",
            GhostRoleKind.RaffleReady => "ghost-roles-window-join-raffle-button",
            GhostRoleKind.RaffleInProgress => "ghost-roles-window-raffle-in-progress-button",
            GhostRoleKind.RaffleJoined => "ghost-roles-window-leave-raffle-button",
            _ => throw new ArgumentOutOfRangeException(nameof(_ghostRoleKind),
                $"Unknown {nameof(GhostRoleKind)} '{_ghostRoleKind}'")
        };

        if (IsActiveRaffle(_ghostRoleKind))
        {
            var timeLeft = _timing.CurTime <= _raffleEndTime
                ? _raffleEndTime - _timing.CurTime
                : TimeSpan.Zero;

            var timeString = $"{timeLeft.Minutes:0}:{timeLeft.Seconds:00}";
            RequestButton.Text = Loc.GetString(messageId, ("time", timeString), ("players", _playerCount));
        }
        else if (_isPurchasableRole)
        {
            var timerSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<GhostRolePurchaseTimerSystem>();
            if (timerSystem.IsTimerActive())
            {
                var timeLeft = timerSystem.GetRemainingTime();
                var timeString = $"{timeLeft.Minutes:0}:{timeLeft.Seconds:00}";
                RequestButton.Text = $"{timeString} - Недоступно";
                RequestButton.Disabled = true;
            }
            else
            {
                RequestButton.Text = $"{_rolePrice} 🪙";
                RequestButton.Disabled = false;
            }
        }
        else
        {
            RequestButton.Text = Loc.GetString(messageId);
        }
    }

    private static bool IsActiveRaffle(GhostRoleKind kind)
    {
        return kind is GhostRoleKind.RaffleInProgress or GhostRoleKind.RaffleJoined;
    }

    private static bool IsPurchasableRole(GhostRoleInfo ghostRoleInfo)
    {
        if (ghostRoleInfo.RolePrototypes.Item2 == null)
            return false;

        var purchasableRoles = new HashSet<string>
        {
            "Thief", "Agent", "Ninja", "Dragon", "Abductor", "InitialInfected",
            "Revenant", "Yao", "RevolutionaryHead", "SpaceCultist", "Blob",
            "Wizard", "SlaughterDemon", "Heretic", "Changeling", "Shadowling",
            "Slasher", "Xenomorph", "Bingle"
        };

        return ghostRoleInfo.RolePrototypes.Item2.Any(antagId => 
            purchasableRoles.Any(role => role.Equals(antagId.Id, StringComparison.OrdinalIgnoreCase)));
    }

    private static int GetRolePrice(GhostRoleInfo ghostRoleInfo)
    {
        if (ghostRoleInfo.RolePrototypes.Item2 == null)
            return 0;

        foreach (var antagId in ghostRoleInfo.RolePrototypes.Item2)
        {
            if (GhostRolePriceCatalog.TryGetPrice(antagId.Id, out var price))
                return price;
        }

        return 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (IsActiveRaffle(_ghostRoleKind) || _isPurchasableRole)
        {
            UpdateRequestButton();
        }
    }
}